export const siteConfig = {
  name: "Baoren Liu",
  description:
    "Computer Science + Mathematics student at UIUC, working on AI research, full-stack applications, and infrastructure.",
  links: {
    github: "https://github.com/RoboticReaper",
    linkedin: "https://www.linkedin.com/in/baoren-liu/",
    instagram: "https://www.instagram.com/littleant2333/",
    discord: "https://discord.com/users/1294767398972428391",
    resume: "/Baoren Liu Resume.pdf",
  },
};
export const projects = [
  {
    title: "OtherWise",
    category: "Semantic discovery",
    description:
      "A discovery system and Chrome extension that connects familiar interests with new topics using keyword embeddings and interactive topic maps.",
    impact: "October 2026",
    tags: ["Python", "SentenceTransformer", "FastAPI", "PCA / UMAP"],
    href: "/projects/otherwise",
    external: "https://roboticreaper.github.io/OtherWise/",
    image: "/otherwise.png",
    tone: "lavender",
  },
  {
    title: "RideList",
    category: "Campus ridesharing",
    description:
      "A bilingual ridesharing app with privacy-preserving ride matching, real-time messaging, and a self-hosted PostgreSQL database secured with mTLS.",
    impact: "Maintained side project",
    tags: ["Next.js", "PostgreSQL", "PostGIS", "Cloudflare"],
    href: "/projects/ridelist",
    external: "https://www.ridelist.app/",
    image: "/ridelist.svg",
    tone: "blue",
  },
  {
    title: "RateMySchedule",
    category: "Schedule analysis",
    description:
      "A course schedule analyzer that combines UIUC course and grading data with a locally hosted LLM to estimate workload and difficulty.",
    impact: "March — May 2026",
    tags: ["React", "Flask", "PostgreSQL", "Ollama"],
    href: "https://github.com/RoboticReaper/RateMySchedule",
    external: "https://github.com/RoboticReaper/RateMySchedule",
    image: null,
    tone: "mint",
  },
  {
    title: "UI-LogOut",
    category: "Chrome extension",
    description:
      "A Chrome extension I made for personal convenience that detects and fixes UIUC Self-Service’s outdated-cookie bug.",
    impact: "Personal convenience tool",
    tags: ["Chrome", "Cookies"],
    href: "https://github.com/RoboticReaper/UI-LogOut",
    external: "https://github.com/RoboticReaper/UI-LogOut",
    image: "/ui-logout.webp",
    tone: "blue",
  },
  {
    title: "EHR Support Agent",
    category: "Agentic systems",
    description:
      "A small agentic customer support demo for electronic health records, built with LangGraph.",
    impact: "LangGraph demo",
    tags: ["LangGraph", "AI agents"],
    href: "https://github.com/RoboticReaper/Customer-Service-Agent-For-EHR",
    external: "https://github.com/RoboticReaper/Customer-Service-Agent-For-EHR",
    image: null,
    tone: "lavender",
  },
  {
    title: "Stridez",
    category: "Database class project",
    description:
      "A Strava clone built with MySQL and Next.js for a database class at Northeastern University.",
    impact: "NEU · CS3200",
    tags: ["MySQL", "Next.js"],
    href: "https://github.com/RoboticReaper/CS3200-Strava-Project",
    external: "https://github.com/RoboticReaper/CS3200-Strava-Project",
    image: "/stridez-welcome.webp",
    tone: "peach",
  },
  {
    title: "ResNet Transfer Learning",
    category: "Computer vision",
    description:
      "Real-time webcam image classification using ResNet-50 transfer learning, with a frozen ImageNet backbone and a custom classification head trained in PyTorch.",
    impact: "March 2025",
    tags: ["PyTorch", "Torchvision", "OpenCV", "CUDA"],
    href: "https://github.com/RoboticReaper/ResNet-Transfer-Learning",
    external: "https://github.com/RoboticReaper/ResNet-Transfer-Learning",
    image: null,
    tone: "lavender",
  },
  {
    title: "Fourier Series Visualizer",
    category: "Math × code",
    description:
      "A visualizer that uses Fourier series to draw SVGs and 2D parametric curves.",
    impact: "SVG and parametric curves",
    tags: ["Python", "Mathematics"],
    href: "/projects/fourier-series",
    external: "https://github.com/RoboticReaper/Fourier-Series-Visualization",
    image: null,
    tone: "peach",
  },
  {
    title: "Naive Bayes Spam Detection",
    category: "Machine learning",
    description:
      "A spam classifier using Naive Bayes, inspired by my discrete structures class.",
    impact: "Naive Bayes classifier",
    tags: ["Python", "Machine learning"],
    href: "/projects/naive-bayes-spam",
    external: "https://github.com/RoboticReaper/NaiveBayesSpam",
    image: null,
    tone: "mint",
  },
  {
    title: "Coaching Website",
    category: "Full-stack application",
    description:
      "A tennis coaching website with lesson bookings, content editing, direct messaging, and Stripe payments. Development is paused.",
    impact: "Development paused",
    tags: ["Web development", "Stripe"],
    href: "/projects/coaching-website",
    external: "https://github.com/RoboticReaper/barry-website",
    image: null,
    tone: "blue",
  },
  {
    title: "LHS Schedule",
    category: "Web application",
    description:
      "A school schedule app with real-time updates, cross-device sync, offline access, PDF schedule importing, and social features.",
    impact: "July 2020 — December 2024",
    tags: ["React", "Material UI", "Firebase", "Netlify"],
    href: "/projects/lhsschedule",
    external: "https://lhsschedule.netlify.app/",
    image: "/schedule_interface.png",
    tone: "mint",
  },
  {
    title: "Notes",
    category: "Android application",
    description:
      "A native Android notes app distributed on third-party app stores.",
    impact: "7k+ downloads",
    tags: ["Kotlin", "Android"],
    href: "/projects/notes",
    external: "https://com-hoversfw-notes.en.aptoide.com/app",
    image: "/Notes.jpg",
    tone: "lavender",
  },
];
