name: Daily API Request

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  request-api:
    runs-on: ubuntu-latest

    steps:
      - name: Send API Request
        run: |
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" https://baorenliu.com/api/cron